#!/usr/bin/env python3
# This file is placed in the Public Domain.
#
# pylint: disable=C,I,R


"environment"


import os
import sys


NAME = "sbn"


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.strip())
        sys.stdout.flush()


popen("cin/clean -f")
popen("cin/builder")
popen("python3 -mvirtualenv --system-site-packages env")
popen("env/bin/pip3 install %s -f dist --upgrade" % NAME)
